name = "wheredidiputit"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
CF_ACCESS_TEAM = "constructly"

[[d1_databases]]
binding = "DB"
database_name = "wdpi-db"
database_id = "f55694fa-d678-4d7c-8ba4-4631ac90b225"
